In [22]:
import pandas as pd

# 1. Read a .csv from a URL with pandas

### Traget website : 'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [23]:
# reading 1 csv file from the website 
df_Premir26 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [70]:
# show data frame
df_Premir26.head()

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [25]:
# rename the columns 
df_Premir26.rename(columns={'FTHG': 'home_goals',
                            'FTAG': 'away_goals'},inplace =True)

In [26]:
# show dataframe
df_Premir26

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

## 2. Read .csv from multiple URLs with pandas

### Link : root + season + league

• https://www.football-data.co.uk/mmz4281/2526/E0.csv
•https://www.football-data.co.uk/mmz4281/2526/E1.csv

In [27]:
# link structure 
'https://www.football-data.co.uk/mmz4281' + '2526' + '/' + 'E1' + '.csv'

'https://www.football-data.co.uk/mmz42812526/E1.csv'

In [30]:
# create a root varabile 
root = 'https://www.football-data.co.uk/mmz4281/'

# 2.1 multiple leagues

•  https://www.football-data.co.uk/mmz4281/2526/E0.csv
•  https://www.football-data.co.uk/mmz4281/2526/E1.csv
•  https://www.football-data.co.uk/mmz4281/2526/E2.csv
•  https://www.football-data.co.uk/mmz4281/2526/E3.csv
•  https://www.football-data.co.uk/mmz4281/2526/EC.csv

In [31]:
# creating list of leagues 
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []
# loop thorugh leagues, read multiple .csv and append it into the list
for league in leagues:
    df = pd.read_csv(root + '2526' + '/' + league + '.csv', encoding='unicode_escape')
    frames.append(df)

In [32]:
# length of frame
len(frames)

5

In [37]:
# show 1st, 2nd, 3rd elements
frames[4]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN

# 2.2 Multiple season

In [40]:
for season in range (15,26):
    print(str(season) + str(season+1))

1516
1617
1718
1819
1920
2021
2122
2223
2324
2425
2526

In [48]:
# creating list of leagues
leagues = ['E0','E2', 'E3']
frames = []
# loop through range of seasons and insert new columns
for league in leagues:
    for season in range(15,26):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv')
        df.insert(1, 'season',season)
        frames.append(df)

In [49]:
# total frame (11 seasons x 3 leagues )
len(frames)

33

In [56]:
# so 1 st and last element (new season columns was create)
frames[0]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

# 3. Organize All the data in a dictionary

In [59]:
# Create a dictionary with original name of league as key
dict_countries = {'spanish La Liga': 'SP1', 'Spanish Segunda Division' : 'SP2',
                  'German Bundesliga':'D1',
                  'English premer leaggue':'E0',
                  'English league 1':'E2',
                  'English league 2':'E3'}

In [58]:
# get a dictionary element 
dict_countries['spanish La Liga']

'SP1'

In [62]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E2
E3

In [64]:
dict_historical_data = {}

# creating list of leagues
for league in dict_countries:
    for season in range(15,26):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv')
        df.insert(1, 'season',season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [67]:
# show dataframe inside dict_historcal_data 
dict_historical_data.keys()

dict_keys(['spanish La Liga', 'Spanish Segunda Division', 'German Bundesliga', 'English premer leaggue', 'English league 1', 'English league 2'])

In [68]:
# show dataframe inside dict_historcal_data 
dict_historical_data['spanish La Liga']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA,Unnamed: 132
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0.0,1.0,A,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2.0,2.0,D,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2.0,2.0,D,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4.0,2.0,H,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,25,23/05/2026,Girona,Elche,1.0,1.0,D,0.0,1.0,...,1.75,3.80,4.40,1.80,3.8,4.20,1.80,3.75,4.20,NaN
376,SP1,25,23/05/2026,Mallorca,Oviedo,3.0,0.0,H,1.0,0.0,...,1.45,4.33,7.50,1.48,4.4,6.50,1.48,4.40,6.50,NaN
377,SP1,25,23/05/2026,Real Madrid,Ath Bilbao,4.0,2.0,H,2.0,1.0,...,1.53,4.60,5.50,1.55,4.8,5.00,1.55,4.60,5.00,NaN
378,SP1,25,23/05/2026,Valencia,Barcelona,3.0,1.0,H,0.0,0.0,...,3.40,4.10,1.93,3.40,4.0,1.95,3.30,4.00,1.95,NaN
379,SP1,25,24/05/2026,Villarreal,Ath Madrid,5.0,1.0,H,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.40,3.80,2.60,NaN